apiVersion: v1
kind: Service
metadata:
  name: produto-api-service
spec: # Descreve o estado desejado do serviço
  selector:
    app: produto-api # para destinar os pods com esta tag
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80  # A porta na qual os pods selecionados pelo seletor atendem.
  type: NodePort  # tipo do serviço (outras opções incluem ClusterIP, LoadBalancer, etc.)
